plugins {
    id "com.android.application"
}

android {
    namespace "com.exonity.wallpaper"
    compileSdk 34

    defaultConfig {
        applicationId "com.exonity.wallpaper"
        minSdk 16
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
